name: gee-blog
env: prod
host: 127.0.0.1
port: 9012
version: v0.0.1
start_time: "2023-05-01"
machine_id: 69  # 机器ID必须在0-1023之间

logger:
  level: info
  filename: gee.log
  director: log
  max_size: 200
  max_age: 30
  max_backups: 7
  show_line: true
  log-in-console: true

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 9012
  dbname: gee_blog
  max_open_conn: 200
  max_idle_conn: 50
  log_level: dev

redis:
  host: 127.0.0.1
  port: 6379
  db: 0
  pool_size: 100
  password:




